server:
  port: 1234

spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: validate
  show-sql: true
  hibernate.dialect: org.hibernate.dialect.MySQL55Dialect

spring.datasource:
  url: jdbc:mysql://localhost:3306/patient
  username: root
  password: test